New registration with alumni option
gurovic/linkedin pull request #159
Opened 2024-12-10 07:55 UTC by andBush

2024-12-10 10:51 UTC, gurovic requested changes

2024-12-10 10:51 UTC, gurovic commented on web/app/templates/app/register.html
При неверном выборе пароля он сбрасывает флажок Выпускник и загруженную картинку (но не сбрасывает логин)

2024-12-10 10:51 UTC, gurovic commented on web/app/templates/app/register.html
А Фамилию и имя при регистрации вводить не нужно?

2024-12-10 10:51 UTC, gurovic commented on web/app/models/__init__.py
> +from .alumni_verification_request import AlumniVerificationRequest
не появляется VerificationRequest при регистрации

2024-12-10 10:51 UTC, gurovic commented on web/app/templates/app/register.html
> +        {{ image_form.as_p }}
а зачем это две разные формы? от этого много проблем будет

2024-12-10 10:51 UTC, gurovic commented on web/app/models/image.py
> +    image_path = models.ImageField(upload_to="images/", blank=True, null=True)
папку хорошо бы назвать как-то осмысленно

2024-12-10 13:31 UTC, andBush commented on web/app/templates/app/register.html
> +        {{ image_form.as_p }}
Одна из них встроенная и работает с модель User, а другая кастомная и работает с классом Image

2024-12-10 13:33 UTC, andBush commented on web/app/models/__init__.py
> +from .alumni_verification_request import AlumniVerificationRequest
Это не я:) Артем Кулаков писал, а мы пока не связывали его реквесты и мои фотографии. В ближайшем будущем все исправим.

2024-12-10 13:43 UTC, andBush commented on web/app/templates/app/register.html
Сделаю, чтобы сохранялось все кроме пароля, потому что если человек ввел все данные, но ошибся с паролем, и из-за этого все удалилось, ему будет грустно.

2024-12-12 10:43 UTC, il-an commented on web/app/templates/app/register.html
добавил

2024-12-12 11:04 UTC, il-an commented on web/app/models/image.py
> +    image_path = models.ImageField(upload_to="images/", blank=True, null=True)
теперь document_photo

2024-12-12 11:07 UTC, il-an commented on web/app/models/__init__.py
> +from .alumni_verification_request import AlumniVerificationRequest
теперь появляется

2024-12-12 19:57 UTC, merged